# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.cache/wt [current_project]
set_property parent.project_path C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/sources_1/new/test2.vhd
  C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/sources_1/imports/new/test1.vhd
  C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/sources_1/new/out_reg.vhd
  C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/sources_1/new/operation.vhd
  C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/sources_1/new/Nregister.vhd
  C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/sources_1/imports/new/mux2_display.vhd
  C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/sources_1/new/ireg.vhd
  C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/sources_1/new/fact_mux.vhd
  C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/sources_1/new/control_unit.vhd
  C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/sources_1/new/Areg.vhd
  C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/sources_1/imports/new/X7seg.vhd
  C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/sources_1/imports/new/clk_divisor.vhd
  C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/sources_1/new/test1.vhd
  C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/sources_1/new/top_algorithm.vhd
  C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/sources_1/imports/new/debounce.vhd
  C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/sources_1/imports/new/clk_pulse.vhd
  C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/sources_1/new/Top_top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/constrs_1/imports/Downloads/Basys-3-Master.xdc
set_property used_in_implementation false [get_files C:/Users/usuario/Factorial_Algorithm_/Factorial_Algorithm_.srcs/constrs_1/imports/Downloads/Basys-3-Master.xdc]


synth_design -top Top_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Top_top.dcp

catch { report_utilization -file Top_top_utilization_synth.rpt -pb Top_top_utilization_synth.pb }
